name: change-blindness
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - zeromq
  - pip:
      - -r backend/requirements.txt
      - -r generation/requirements.txt
      - -r generation/requirements-dev.txt
